# Generated by Django 4.2.30 on 2026-04-27 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='ملغى')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('invoice_number', models.CharField(max_length=32, unique=True, verbose_name='رقم فاتورة الشراء')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع'), ('partial', 'جزئي'), ('unpaid', 'آجل')], default='paid', max_length=16, verbose_name='حالة السداد')),
            ],
            options={
                'verbose_name': 'فاتورة شراء',
                'verbose_name_plural': 'فواتير الشراء',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد (لنا / علينا)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك'), ('credit', 'من الرصيد / تسوية')], max_length=16, verbose_name='طريقة الدفع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.supplier', verbose_name='المورد')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'سداد مورد',
                'verbose_name_plural': 'سدادات الموردين',
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('entry_type', models.CharField(choices=[('purchase', 'مشتريات'), ('payment', 'سداد للمورد'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع القيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ (+ علينا للمورد / - سداد)')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('reference_model', models.CharField(blank=True, max_length=128, verbose_name='مرجع')),
                ('reference_pk', models.CharField(blank=True, max_length=64, verbose_name='معرف المرجع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='purchasing.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'قيد مورد',
                'verbose_name_plural': 'دفتر الموردين',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='المنتج')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseinvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'سطر شراء',
                'verbose_name_plural': 'أسطر الشراء',
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='purchasing.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='work_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='core.worksession', verbose_name='الوردية'),
        ),
    ]
