# Generated by Django 4.2.30 on 2026-04-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='linked_customer',
            field=models.OneToOneField(blank=True, help_text='إذا كان المورد يشتري منا أيضاً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_supplier', to='contacts.customer', verbose_name='حساب العميل المرتبط'),
        ),
    ]
