# Generated by Django 4.2.30 on 2026-04-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_barcode'),
        ('purchasing', '0002_supplier_linked_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('return_number', models.CharField(max_length=32, unique=True, verbose_name='رقم المرتجع')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchasing.purchaseinvoice', verbose_name='فاتورة الشراء')),
            ],
            options={
                'verbose_name': 'مرتجع مشتريات',
                'verbose_name_plural': 'مرتجعات المشتريات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية المرتجعة')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='تكلفة الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='المنتج')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchasereturn', verbose_name='المرتجع')),
            ],
            options={
                'verbose_name': 'سطر مرتجع مشتريات',
                'verbose_name_plural': 'أسطر مرتجع المشتريات',
            },
        ),
    ]
