# Generated by Django — SupplierCafePurchase

import django.db.models.deletion
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_worksession_opening_balances_json"),
        ("billing", "0008_saleinvoiceline_manufacturing_finished_qty"),
        ("purchasing", "0006_supplier_is_commission_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierCafePurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name="المبلغ")),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة")),
                (
                    "sale_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_cafe_purchases",
                        to="billing.saleinvoice",
                        verbose_name="فاتورة مرتبطة",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafe_purchases",
                        to="purchasing.supplier",
                        verbose_name="المورد",
                    ),
                ),
                (
                    "work_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_cafe_purchases",
                        to="core.worksession",
                        verbose_name="الوردية",
                    ),
                ),
            ],
            options={
                "verbose_name": "شراء مورد من المقهى (آجل)",
                "verbose_name_plural": "مشتريات الموردين من المقهى",
                "ordering": ("-created_at",),
            },
        ),
    ]
