# Generated by Django 4.2.30 on 2026-04-27 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        ('core', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='ملغى')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('invoice_number', models.CharField(max_length=32, unique=True, verbose_name='رقم الفاتورة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع قبل الخصم')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الخصم')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي التكلفة')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الربح المعترف')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع بالكامل'), ('partial', 'جزئي'), ('unpaid', 'غير مدفوع')], default='paid', max_length=16, verbose_name='حالة السداد')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer', verbose_name='عميل ائتمان')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoice', to='pos.order', verbose_name='الطلب')),
                ('supplier_buyer', models.ForeignKey(blank=True, help_text='اختياري: بيع لمورد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.supplier', verbose_name='مورد مشتري من المقهى')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'verbose_name_plural': 'فواتير البيع',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر البيع')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='تكلفة الوحدة وقت البيع')),
                ('line_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي التكلفة')),
                ('recognized_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإيراد المعترف')),
                ('line_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الربح المعترف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.saleinvoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سطر فاتورة',
                'verbose_name_plural': 'أسطر الفواتير',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك / بطاقة'), ('credit', 'حساب عميل')], max_length=16, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.saleinvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة فاتورة',
                'verbose_name_plural': 'دفعات الفواتير',
            },
        ),
    ]
