# Generated by Django 4.2.30 on 2026-04-27 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='service_charge_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي خدمة'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي ضريبة'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك / بطاقة'), ('credit', 'حساب عميل')], max_length=16, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_payments', to='pos.order', verbose_name='الطلب')),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_tab_payments', to='billing.saleinvoice', verbose_name='فاتورة التسوية')),
            ],
            options={
                'verbose_name': 'دفعة على طلب',
                'verbose_name_plural': 'دفعات الطلب (تاب)',
            },
        ),
    ]
