# Generated by Django 4.2.30 on 2026-04-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_barcode'),
        ('billing', '0002_pos_advanced'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('return_number', models.CharField(max_length=32, unique=True, verbose_name='رقم المرتجع')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('total_refund', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي المرتجع')),
                ('refund_method', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'رصيد عميل')], default='cash', max_length=16, verbose_name='طريقة الاسترداد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.saleinvoice', verbose_name='الفاتورة الأصلية')),
            ],
            options={
                'verbose_name': 'مرتجع بيع',
                'verbose_name_plural': 'مرتجعات البيع',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='المنتج')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.salereturn', verbose_name='المرتجع')),
            ],
            options={
                'verbose_name': 'سطر مرتجع',
                'verbose_name_plural': 'أسطر المرتجع',
            },
        ),
    ]
