# Generated by Django 4.2.30 on 2026-04-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_salereturn_salereturnline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تطبيق'), ('credit', 'آجل')], max_length=16, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'تطبيق'), ('credit', 'آجل')], max_length=16, verbose_name='طريقة الدفع'),
        ),
    ]
