# Generated by Django 4.2.27 on 2026-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_update_payment_method_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'شبكة (عام)'), ('bank_ps', 'بنك فلسطين'), ('palpay', 'بال باي'), ('jawwalpay', 'جوال باي'), ('credit', 'آجل')], max_length=16, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('bank', 'شبكة (عام)'), ('bank_ps', 'بنك فلسطين'), ('palpay', 'بال باي'), ('jawwalpay', 'جوال باي'), ('credit', 'آجل')], max_length=16, verbose_name='طريقة الدفع'),
        ),
    ]
