# Generated by Django 4.2.27 on 2026-04-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoicepayment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='method',
            field=models.CharField(max_length=32, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='method',
            field=models.CharField(max_length=32, verbose_name='طريقة الدفع'),
        ),
    ]
