# Generated by Django 4.2.27 on 2026-05-21 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_receipt_show_work_session_help'),
        ('billing', '0008_saleinvoiceline_manufacturing_finished_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='work_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='core.worksession', verbose_name='الوردية'),
        ),
    ]
