# Generated by Django 4.2.30 on 2026-04-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد (عليه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('entry_type', models.CharField(choices=[('invoice', 'فاتورة بيع آجل'), ('payment', 'سداد'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع القيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ (+ دين / - سداد)')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('reference_model', models.CharField(blank=True, max_length=128, verbose_name='مرجع')),
                ('reference_pk', models.CharField(blank=True, max_length=64, verbose_name='معرف المرجع')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='contacts.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'قيد عميل',
                'verbose_name_plural': 'دفتر العملاء',
                'ordering': ('-created_at',),
            },
        ),
    ]
