# Generated by Django 4.2.27 on 2026-05-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد (+ مدين عليه / − دائن له)'),
        ),
    ]
