# Generated by Django 4.2.30 on 2026-04-27 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdSequence',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='المفتاح')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'تسلسل معرفات',
                'verbose_name_plural': 'تسلسلات المعرفات',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=16, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت فتح الوردية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الصندوق الافتتاحي')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الصندوق الختامي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='أغلقها')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='فتحها')),
            ],
            options={
                'verbose_name': 'وردية عمل',
                'verbose_name_plural': 'ورديات العمل',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='الإجراء')),
                ('model_label', models.CharField(blank=True, max_length=128, verbose_name='النموذج')),
                ('object_pk', models.CharField(blank=True, max_length=64, verbose_name='معرف السجل')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ('-created_at',),
            },
        ),
    ]
