# Generated by Django 4.2.30 on 2026-04-27 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('default_tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ضريبة افتراضية %')),
                ('default_service_charge_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='خدمة افتراضية %')),
                ('kitchen_auto_print', models.BooleanField(default=False, verbose_name='طباعة مطبخ تلقائية')),
                ('printer_kitchen_label', models.CharField(blank=True, max_length=120, verbose_name='اسم طابعة المطبخ (مستقبلي)')),
                ('printer_receipt_label', models.CharField(blank=True, max_length=120, verbose_name='اسم طابعة الإيصال (مستقبلي)')),
            ],
            options={
                'verbose_name': 'إعدادات نقطة البيع',
                'verbose_name_plural': 'إعدادات نقطة البيع',
            },
        ),
    ]
