# Generated by Django 4.2.30 on 2026-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pos_advanced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possettings',
            options={'verbose_name': 'إعدادات النظام', 'verbose_name_plural': 'إعدادات النظام'},
        ),
        migrations.AddField(
            model_name='possettings',
            name='allow_negative_stock',
            field=models.BooleanField(default=True, verbose_name='السماح بمخزون سالب'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='cafe_address',
            field=models.TextField(blank=True, verbose_name='عنوان المقهى'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='cafe_name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المقهى (عربي)'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='cafe_name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المقهى (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='cafe_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='هاتف المقهى'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='cafe_tax_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='currency_code',
            field=models.CharField(default='SAR', max_length=8, verbose_name='كود العملة'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='currency_symbol',
            field=models.CharField(default='ر.س', max_length=8, verbose_name='رمز العملة'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='خانات عشرية'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='default_order_type',
            field=models.CharField(choices=[('dine_in', 'صالة'), ('takeaway', 'سفري'), ('delivery', 'توصيل')], default='dine_in', max_length=16, verbose_name='نوع الطلب الافتراضي'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='receipt_footer',
            field=models.TextField(blank=True, verbose_name='تذييل الإيصال (نص إضافي)'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='receipt_header',
            field=models.TextField(blank=True, verbose_name='رأس الإيصال (نص إضافي)'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='receipt_show_tax_number',
            field=models.BooleanField(default=True, verbose_name='إظهار الرقم الضريبي على الإيصال'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='require_customer_for_credit',
            field=models.BooleanField(default=True, verbose_name='يجب تحديد عميل للبيع الآجل'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='tax_included_in_price',
            field=models.BooleanField(default=False, verbose_name='الضريبة مشمولة في السعر'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='printer_kitchen_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم طابعة المطبخ'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='printer_receipt_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم طابعة الإيصال'),
        ),
    ]
