# Generated by Django 4.2.30 on 2026-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expanded_settings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('status',), name='unique_open_session'),
        ),
    ]
