# Generated by Django 4.2.27 on 2026-04-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unique_open_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='payment_methods_json',
            field=models.JSONField(blank=True, default=list, verbose_name='طرق الدفع (JSON)'),
        ),
    ]
