# Generated by Django 4.2.27 on 2026-04-28 22:12

import django.core.validators
from django.db import migrations, models


DEFAULT_ROWS = [
    {"code": "cash", "label_ar": "كاش", "label_en": "", "ledger": "cash", "sort_order": 0},
    {"code": "bank_ps", "label_ar": "بنك فلسطين", "label_en": "", "ledger": "bank", "sort_order": 10},
    {"code": "palpay", "label_ar": "بال باي", "label_en": "", "ledger": "bank", "sort_order": 20},
    {"code": "jawwalpay", "label_ar": "جوال باي", "label_en": "", "ledger": "bank", "sort_order": 30},
    {"code": "credit", "label_ar": "آجل", "label_en": "", "ledger": "ar", "sort_order": 40},
]


def forwards_seed_payment_methods(apps, schema_editor):
    PosSettings = apps.get_model("core", "PosSettings")
    PaymentMethod = apps.get_model("core", "PaymentMethod")
    if PaymentMethod.objects.exists():
        return
    s = PosSettings.objects.filter(pk=1).first()
    raw = getattr(s, "payment_methods_json", None) if s else None
    rows = []
    if isinstance(raw, list) and raw:
        for i, item in enumerate(raw):
            if not isinstance(item, dict):
                continue
            code = str(item.get("code", "")).strip().lower()[:32]
            label_ar = str(item.get("label_ar", "")).strip()[:120]
            ledger = str(item.get("ledger", "bank")).strip().lower()[:8]
            if not code or not label_ar or ledger not in ("cash", "bank", "ar"):
                continue
            rows.append(
                {
                    "code": code,
                    "label_ar": label_ar,
                    "label_en": str(item.get("label_en", "")).strip()[:120],
                    "ledger": ledger,
                    "sort_order": i * 10,
                    "is_active": True,
                }
            )
    if not rows:
        rows = [dict(r, is_active=True) for r in DEFAULT_ROWS]
    seen = set()
    for r in rows:
        c = r["code"]
        if c in seen:
            continue
        seen.add(c)
        PaymentMethod.objects.create(**r)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_possettings_payment_methods_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='لاتيني صغير، للاستخدام الداخلي (مثل cash، bank_ps).', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{0,31}$', 'رمز لاتيني صغير: يبدأ بحرف ثم أرقام أو _.')], verbose_name='رمز النظام')),
                ('label_ar', models.CharField(max_length=120, verbose_name='الاسم المعروض')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنجليزي)')),
                ('ledger', models.CharField(choices=[('cash', 'صندوق نقدي'), ('bank', 'بنك / شبكة'), ('ar', 'آجل / ذمم')], default='bank', max_length=8, verbose_name='نوع الحساب المحاسبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.RunPython(forwards_seed_payment_methods, noop_reverse),
        migrations.RemoveField(
            model_name='possettings',
            name='payment_methods_json',
        ),
    ]
