# Generated by Django 4.2.27 on 2026-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_worksession_opening_balances_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='receipt_label_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='يُدار من نموذج الإيصال — مفاتيح نصية تستبدل العناوين الافتراضية.', verbose_name='عبارات الإيصال (تخصيص اختياري)'),
        ),
    ]
