# Generated by Django 4.2.27 on 2026-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_possettings_receipt_label_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='receipt_show_work_session',
            field=models.BooleanField(default=True, verbose_name='إظهار الوردية على الإيصال'),
        ),
    ]
