# Generated by Django 4.2.27 on 2026-05-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_possettings_receipt_show_work_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possettings',
            name='receipt_show_work_session',
            field=models.BooleanField(default=True, help_text='عطّله لإخفاء سطر الوردية من الإيصال الحراري ومن معاينة الفاتورة في الغلاف.', verbose_name='إظهار الوردية على الإيصال'),
        ),
    ]
