# Generated by Django 4.2.27 on 2026-05-21 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_seed_discount_voucher_accounts'),
        ('core', '0012_alter_receipt_show_work_session_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='gl_account',
            field=models.ForeignKey(blank=True, help_text='حساب فرعي للصندوق/البنك — يُنشأ تلقائياً لطرق cash/bank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='accounting.account', verbose_name='حساب محاسبي'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='operation_mode',
            field=models.CharField(choices=[('shifts', 'ورديات عمل'), ('continuous', 'محاسبة مستمرة')], default='continuous', help_text='ورديات: فتح/إغلاق وردية ومطابقة صناديق. مستمر: بيع بدون وردية وتقرير الصناديق بالفترة.', max_length=16, verbose_name='نمط العمل'),
        ),
        migrations.CreateModel(
            name='PaymentChannelBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='رصيد افتتاحي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_balance', to='core.paymentmethod', verbose_name='طريقة الدفع')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_channel_balance_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخر مُحدِّث')),
            ],
            options={
                'verbose_name': 'رصيد صندوق',
                'verbose_name_plural': 'أرصدة الصناديق',
            },
        ),
        migrations.CreateModel(
            name='BalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_delta', models.DecimalField(decimal_places=2, help_text='موجب يزيد الرصيد، سالب ينقصه.', max_digits=14, verbose_name='مبلغ التسوية')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('effective_date', models.DateField(verbose_name='تاريخ التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_adjustments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_adjustments', to='accounting.journalentry', verbose_name='قيد يومي')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to='core.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'تسوية رصيد صندوق',
                'verbose_name_plural': 'تسويات أرصدة الصناديق',
                'ordering': ('-effective_date', '-pk'),
            },
        ),
    ]
