# Generated by Django 4.2.30 on 2026-04-27 15:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_pos_advanced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='رمز الحساب')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=16, verbose_name='نوع الحساب')),
                ('system_code', models.CharField(blank=True, help_text='للربط التلقائي: CASH, BANK, AR, INVENTORY...', max_length=40, null=True, unique=True, verbose_name='رمز النظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('entry_number', models.CharField(max_length=32, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, db_index=True, help_text='مثل: billing.SaleInvoice, purchasing.PurchaseInvoice', max_length=64, verbose_name='نوع المرجع')),
                ('reference_pk', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='معرف المرجع')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='معكوس')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='accounting.journalentry', verbose_name='عُكس بواسطة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'قيد يومي',
                'verbose_name_plural': 'القيود اليومية',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='بيان السطر')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'أسطر القيود',
            },
        ),
    ]
