# Generated by Django 4.2.30 on 2026-04-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('movement_type', models.CharField(choices=[('purchase', 'شراء'), ('sale', 'بيع'), ('manufacturing', 'استهلاك تصنيع'), ('adjustment', 'تسوية يدوية'), ('waste', 'هالك / تلف')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity_delta', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='التغيير (+داخل / -خارج)')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='تكلفة الوحدة')),
                ('reference_model', models.CharField(blank=True, max_length=128, verbose_name='مرجع (نموذج)')),
                ('reference_pk', models.CharField(blank=True, max_length=64, verbose_name='مرجع (معرف)')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='المنتج')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='الكمية الحالية')),
                ('average_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='متوسط التكلفة')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'رصيد مخزون',
                'verbose_name_plural': 'أرصدة المخزون',
            },
        ),
    ]
