# Generated by Django 4.2.30 on 2026-04-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expanded_settings'),
        ('catalog', '0004_product_commission_vendor'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد')], default='draft', max_length=16, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'جرد',
                'verbose_name_plural': 'عمليات الجرد',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('system_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='كمية النظام')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='الكمية الفعلية')),
                ('difference', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='الفرق')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='المنتج')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake', verbose_name='الجرد')),
            ],
            options={
                'verbose_name': 'سطر جرد',
                'verbose_name_plural': 'أسطر الجرد',
            },
        ),
    ]
