from django.urls import path

from apps.catalog.views import (
    category_create,
    category_quick_create,
    category_search,
    category_delete,
    category_edit,
    category_list,
    component_info,
    product_card,
    product_create,
    manufactured_product_create,
    product_edit,
    product_list,
    product_workspace,
    product_delete,
    product_toggle_active,
    recipe_add,
    recipe_delete,
    recipe_list,
    unit_create,
    unit_delete,
    unit_edit,
    unit_list,
)

app_name = "catalog"

urlpatterns = [
    path("", product_list, name="product_list"),
    path("workspace/", product_workspace, name="product_workspace"),
    path("create/", product_create, name="product_create"),
    path("manufactured/create/", manufactured_product_create, name="manufactured_product_create"),
    path("<int:pk>/edit/", product_edit, name="product_edit"),
    path("<int:pk>/toggle/", product_toggle_active, name="product_toggle"),
    path("<int:pk>/delete/", product_delete, name="product_delete"),
    path("<int:pk>/card/", product_card, name="product_card"),
    path("<int:pk>/recipe/", recipe_list, name="recipe_list"),
    path("<int:pk>/recipe/add/", recipe_add, name="recipe_add"),
    path("<int:pk>/recipe/<int:line_id>/delete/", recipe_delete, name="recipe_delete"),
    path("categories/", category_list, name="category_list"),
    path("api/categories/search/", category_search, name="category_search"),
    path("api/categories/quick-create/", category_quick_create, name="category_quick_create"),
    path("categories/create/", category_create, name="category_create"),
    path("categories/<int:pk>/edit/", category_edit, name="category_edit"),
    path("categories/<int:pk>/delete/", category_delete, name="category_delete"),
    path("units/", unit_list, name="unit_list"),
    path("units/create/", unit_create, name="unit_create"),
    path("units/<int:pk>/edit/", unit_edit, name="unit_edit"),
    path("units/<int:pk>/delete/", unit_delete, name="unit_delete"),
    path("component/<int:pk>/info/", component_info, name="component_info"),
]
