"""Views package — re-exports for urls and shell imports."""
from apps.pos.views._helpers import _get_order_for_session
from apps.pos.views._helpers import _post_redirect_after_cancel
from apps.pos.views._helpers import _annotate_pos_product_stock
from apps.pos.views._helpers import _money
from apps.pos.views._helpers import _parse_pos_discount_input
from apps.pos.views._helpers import _ajax_or_redirect
from apps.pos.views._helpers import _ajax_or_redirect_error
from apps.pos.views._helpers import _receipt_stamp_lines
from apps.pos.views.settings import redirect_pos_settings_to_app
from apps.pos.views.main import pos_main
from apps.pos.views.main import pos_customer_create_save
from apps.pos.views.main import pos_product_quick_save
from apps.pos.views.main import last_sale_invoice_panel
from apps.pos.views.main import last_sale_invoice_edit_redirect
from apps.pos.views.main import last_invoice_resume_into_cart
from apps.pos.views.main import cart_fragment
from apps.pos.views.main import floor_tables_fragment
from apps.pos.views.main import receipt_print
from apps.pos.views.main import receipt_live_preview
from apps.pos.views.main import receipt_raw
from apps.pos.views.tables import table_open
from apps.pos.views.tables import table_quick_create
from apps.pos.views.search import customers_search
from apps.pos.views.search import products_search
from apps.pos.views.search import customer_quick_create
from apps.pos.views.search import payer_hints_search
from apps.pos.views.orders import customize_product
from apps.pos.views.orders import kitchen_ticket
from apps.pos.views.orders import kitchen_receipt_embed
from apps.pos.views.orders import order_resume
from apps.pos.views.orders import order_new
from apps.pos.views.orders import order_add_product
from apps.pos.views.orders import order_adjust_line
from apps.pos.views.orders import order_remove_line
from apps.pos.views.orders import order_line_note
from apps.pos.views.orders import order_line_unit_price
from apps.pos.views.orders import order_set_customer
from apps.pos.views.orders import order_note
from apps.pos.views.orders import order_discount
from apps.pos.views.orders import order_cancel
from apps.pos.views.orders import order_hold
from apps.pos.views.checkout import _payments_from_checkout_form
from apps.pos.views.checkout import order_checkout
