"""مسارات الغلاف الموحّدة تحت /app/ — الإعدادات (/app/settings/…) والعملاء (/app/customers/…)."""

from django.urls import path

from apps.accounting import views as accounting_views
from apps.billing import views as billing_views
from apps.catalog import views as catalog_views
from apps.contacts import views as contacts_views
from apps.core import payment_method_pages
from apps.core import shell_views
from apps.core import views as core_views
from apps.expenses import views as expenses_views
from apps.inventory import views as inventory_views
from apps.payroll import views as payroll_views
from apps.purchasing import views as purchasing_views
from apps.reports import views as reports_views

app_name = "shell"

urlpatterns = [
    path("settings/", shell_views.settings_page, name="settings"),
    path(
        "settings/payment-methods/",
        payment_method_pages.payment_method_list_page,
        name="payment_methods",
    ),
    path(
        "settings/payment-methods/new/",
        payment_method_pages.payment_method_create_page,
        name="payment_method_create",
    ),
    path(
        "settings/payment-methods/<int:pk>/edit/",
        payment_method_pages.payment_method_update_page,
        name="payment_method_update",
    ),
    path(
        "settings/payment-methods/<int:pk>/delete/",
        payment_method_pages.payment_method_delete_page,
        name="payment_method_delete",
    ),
    path("settings/tables/", core_views.tables_list, name="tables_list"),
    path("settings/tables/create/", core_views.table_create, name="table_create"),
    path("settings/tables/<int:pk>/edit/", core_views.table_edit, name="table_edit"),
    path("settings/tables/<int:pk>/toggle/", core_views.table_toggle, name="table_toggle"),
    path("customers/", contacts_views.customer_list, name="customers"),
    path("customers/balances/", contacts_views.customer_balances, name="customer_balances"),
    path("customers/create/", contacts_views.customer_create, name="customer_create"),
    path("customers/<int:pk>/", contacts_views.customer_detail, name="customer_detail"),
    path("customers/<int:pk>/edit/", contacts_views.customer_edit, name="customer_edit"),
    path("customers/<int:pk>/delete/", contacts_views.customer_delete, name="customer_delete"),
    path("customers/<int:pk>/ledger/<int:entry_pk>/delete/", contacts_views.customer_ledger_delete, name="customer_ledger_delete"),
    path("customers/<int:pk>/payment/", contacts_views.customer_payment, name="customer_payment"),
    path("customers/<int:pk>/statement/", contacts_views.customer_statement, name="customer_statement"),
    path("invoices/<int:pk>/", billing_views.sale_invoice_detail, name="invoice_detail"),
    path("invoices/<int:pk>/edit/", billing_views.sale_invoice_edit, name="sale_invoice_edit"),
    path("suppliers/", purchasing_views.supplier_list, name="suppliers"),
    path("suppliers/balances/", purchasing_views.supplier_balances, name="supplier_balances"),
    path("suppliers/create/", purchasing_views.supplier_create, name="supplier_create"),
    path("suppliers/commission-vendors/", purchasing_views.commission_vendor_report, name="commission_vendors"),
    path("suppliers/<int:pk>/", purchasing_views.supplier_detail, name="supplier_detail"),
    path("suppliers/<int:pk>/edit/", purchasing_views.supplier_edit, name="supplier_edit"),
    path("suppliers/<int:pk>/delete/", purchasing_views.supplier_delete, name="supplier_delete"),
    path("suppliers/<int:pk>/payment/", purchasing_views.supplier_payment_create, name="supplier_payment"),
    path("suppliers/<int:pk>/purchase/", purchasing_views.purchase_invoice_create, name="purchase_create"),
    path("suppliers/<int:pk>/link-customer/", purchasing_views.supplier_link_customer, name="supplier_link_customer"),
    path("suppliers/<int:pk>/statement/", purchasing_views.supplier_statement, name="supplier_statement"),
    path("purchase/api/suppliers/search/", purchasing_views.purchase_suppliers_search, name="purchase_suppliers_search"),
    path("purchase/api/suppliers/quick-create/", purchasing_views.purchase_supplier_quick_create, name="purchase_supplier_quick_create"),
    path("purchase/api/units/search/", purchasing_views.purchase_units_search, name="purchase_units_search"),
    path("purchase/api/units/quick-create/", purchasing_views.purchase_unit_quick_create, name="purchase_unit_quick_create"),
    path("purchase/api/products/search/", purchasing_views.purchase_products_search, name="purchase_products_search"),
    path("purchase/api/products/quick-create/", purchasing_views.purchase_product_quick_create, name="purchase_product_quick_create"),
    path("purchase/new/", purchasing_views.purchase_invoice_new, name="purchase_new"),
    path("purchase/list/", purchasing_views.purchase_invoice_list, name="purchase_list"),
    path("purchase/<int:pk>/delete/", purchasing_views.purchase_invoice_delete, name="purchase_delete"),
    path("purchase/<int:pk>/return/", purchasing_views.purchase_return_create, name="purchase_return"),
    path("purchase/<int:pk>/", purchasing_views.purchase_invoice_detail, name="purchase_detail"),
    path("products/", catalog_views.product_list, name="product_list"),
    path("products/workspace/", catalog_views.product_workspace, name="product_workspace"),
    path("products/api/categories/search/", catalog_views.category_search, name="category_search"),
    path("products/api/categories/quick-create/", catalog_views.category_quick_create, name="category_quick_create"),
    path("products/create/", catalog_views.product_create, name="product_create"),
    path("products/manufactured/create/", catalog_views.manufactured_product_create, name="manufactured_product_create"),
    path("products/<int:pk>/edit/", catalog_views.product_edit, name="product_edit"),
    path("products/<int:pk>/toggle/", catalog_views.product_toggle_active, name="product_toggle"),
    path("products/<int:pk>/card/", catalog_views.product_card, name="product_card"),
    path("products/<int:pk>/delete/", catalog_views.product_delete, name="product_delete"),
    path("products/component/<int:pk>/info/", catalog_views.component_info, name="component_info"),
    path("products/categories/", catalog_views.category_list, name="category_list"),
    path("products/categories/create/", catalog_views.category_create, name="category_create"),
    path("products/categories/<int:pk>/edit/", catalog_views.category_edit, name="category_edit"),
    path("products/categories/<int:pk>/delete/", catalog_views.category_delete, name="category_delete"),
    path("products/units/", catalog_views.unit_list, name="unit_list"),
    path("products/units/create/", catalog_views.unit_create, name="unit_create"),
    path("products/units/<int:pk>/edit/", catalog_views.unit_edit, name="unit_edit"),
    path("products/units/<int:pk>/delete/", catalog_views.unit_delete, name="unit_delete"),
    path("products/<int:pk>/recipe/", catalog_views.recipe_list, name="recipe_list"),
    path("products/<int:pk>/recipe/add/", catalog_views.recipe_add, name="recipe_add"),
    path("products/<int:pk>/recipe/<int:line_id>/delete/", catalog_views.recipe_delete, name="recipe_delete"),
    path("inventory/", inventory_views.inventory_home, name="inventory_home"),
    path("inventory/movements/", inventory_views.movement_list, name="inventory_movements"),
    path("inventory/adjust/", inventory_views.stock_adjust, name="inventory_adjust"),
    path("inventory/raw-materials/", inventory_views.raw_material_list, name="raw_materials"),
    path("inventory/raw-materials/create/", inventory_views.raw_material_create, name="raw_material_create"),
    path("inventory/raw-materials/<int:pk>/edit/", inventory_views.raw_material_edit, name="raw_material_edit"),
    path("inventory/raw-materials/<int:pk>/delete/", inventory_views.raw_material_delete, name="raw_material_delete"),
    path("inventory/raw-materials/<int:pk>/card/", inventory_views.raw_material_card, name="raw_material_card"),
    path("inventory/alerts/", inventory_views.low_stock_alerts, name="low_stock_alerts"),
    path("inventory/stocktake/", inventory_views.stocktake_list, name="stocktake_list"),
    path("inventory/stocktake/create/", inventory_views.stocktake_create, name="stocktake_create"),
    path("inventory/stocktake/<int:pk>/", inventory_views.stocktake_detail, name="stocktake_detail"),
    path("inventory/stocktake/<int:pk>/edit/", inventory_views.stocktake_edit, name="stocktake_edit"),
    path("inventory/stocktake/<int:pk>/approve/", inventory_views.stocktake_approve, name="stocktake_approve"),
    path("expenses/", expenses_views.expense_list, name="expenses"),
    path("expenses/create/", expenses_views.expense_create, name="expense_create"),
    path("expenses/<int:pk>/edit/", expenses_views.expense_edit, name="expense_edit"),
    path("expenses/<int:pk>/delete/", expenses_views.expense_delete, name="expense_delete"),
    path("expenses/categories/", expenses_views.expense_category_list, name="expense_categories"),
    path("expenses/categories/create/", expenses_views.expense_category_create, name="expense_category_create"),
    path("expenses/categories/<int:pk>/edit/", expenses_views.expense_category_edit, name="expense_category_edit"),
    path("reports/", reports_views.reports_dashboard, name="reports"),
    path("reports/daily-sales/", reports_views.daily_sales_report, name="daily_sales"),
    path("reports/expenses/", reports_views.expense_report, name="expense_report"),
    path("reports/weekly/", reports_views.weekly_report, name="weekly_report"),
    path("reports/product-movement/", reports_views.product_movement_report, name="product_movement"),
    path("reports/cash-flow/", reports_views.cash_flow_report, name="cash_flow"),
    path("reports/payroll/", reports_views.payroll_report, name="payroll_report"),
    path("reports/payment-channels/", reports_views.payment_channels_report, name="payment_channels"),
    path("billing/invoices/", billing_views.sale_invoice_list, name="invoice_list"),
    path("billing/invoices/<int:pk>/delete/", billing_views.sale_invoice_delete, name="sale_invoice_delete"),
    path("billing/invoices/customer/<int:customer_id>/", billing_views.customer_invoices, name="customer_invoices"),
    path("billing/invoices/<int:invoice_pk>/return/", billing_views.sale_return_create, name="sale_return"),
    path("accounting/accounts/", accounting_views.chart_of_accounts, name="accounting_chart"),
    path("accounting/accounts/<int:pk>/ledger/", accounting_views.account_ledger_view, name="account_ledger"),
    path("accounting/trial-balance/", accounting_views.trial_balance_view, name="trial_balance"),
    path("accounting/pnl/", accounting_views.pnl_view, name="pnl"),
    path("accounting/journal/", accounting_views.journal_list, name="journal_list"),
    path("accounting/journal/<int:pk>/", accounting_views.journal_detail, name="journal_detail"),
    path("accounting/treasury/", core_views.treasury, name="accounting_treasury"),
    path("accounting/treasury/party-search/", core_views.treasury_party_search, name="treasury_party_search"),
    path("payroll/", payroll_views.employee_list, name="employees"),
    path("payroll/create/", payroll_views.employee_create, name="employee_create"),
    path("payroll/<int:pk>/", payroll_views.employee_detail, name="employee_detail"),
    path("payroll/<int:pk>/edit/", payroll_views.employee_edit, name="employee_edit"),
    path("payroll/<int:pk>/delete/", payroll_views.employee_delete, name="employee_delete"),
    path("payroll/<int:pk>/advance/", payroll_views.employee_advance_create, name="employee_advance"),
    path("payroll/<int:pk>/advance/<int:advance_id>/delete/", payroll_views.employee_advance_delete, name="employee_advance_delete"),
    path("payroll/<int:pk>/payout/", payroll_views.employee_payout_create, name="employee_payout"),
    path("payroll/<int:pk>/payout/<int:payout_id>/delete/", payroll_views.employee_payout_delete, name="employee_payout_delete"),
    path("payroll/<int:pk>/add-days/", payroll_views.employee_add_days, name="employee_add_days"),
    path("payroll/<int:pk>/add-hours/", payroll_views.employee_add_hours, name="employee_add_hours"),
    path("payroll/<int:pk>/cafe-purchase/", payroll_views.employee_cafe_purchase, name="employee_cafe_purchase"),
    path("payroll/<int:pk>/cafe-purchase/<int:purchase_id>/delete/", payroll_views.employee_cafe_purchase_delete, name="employee_cafe_purchase_delete"),
]
