# Generated by Django 4.2.30 on 2026-04-27 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=160, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=160, verbose_name='الاسم (إنجليزي)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='التصنيف الرئيسي')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ('sort_order', 'name_ar'),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=128, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=128, verbose_name='الاسم (إنجليزي)')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر البيع')),
                ('product_type', models.CharField(choices=[('raw', 'مادة خام'), ('ready', 'منتج جاهز'), ('manufactured', 'منتج مصنع'), ('service', 'خدمة'), ('commission', 'عمولة / وسيط')], max_length=20, verbose_name='نوع المنتج')),
                ('is_stock_tracked', models.BooleanField(default=False, verbose_name='تتبع المخزون؟')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة العمولة %')),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الحد الأدنى للمخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='التصنيف')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية لكل وحدة منتج')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='catalog.product', verbose_name='المكوّن')),
                ('manufactured_product', models.ForeignKey(limit_choices_to={'product_type': 'manufactured'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='catalog.product', verbose_name='المنتج المصنع')),
            ],
            options={
                'verbose_name': 'سطر وصفة',
                'verbose_name_plural': 'مكوّنات الوصفات',
                'unique_together': {('manufactured_product', 'component')},
            },
        ),
    ]
