# Generated by Django 4.2.30 on 2026-04-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=120, verbose_name='اسم المجموعة')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنجليزي)')),
                ('min_select', models.PositiveSmallIntegerField(default=0, verbose_name='حد أدنى للاختيار')),
                ('max_select', models.PositiveSmallIntegerField(default=1, verbose_name='حد أقصى للاختيار')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مجموعة معدّلات',
                'verbose_name_plural': 'مجموعات المعدّلات',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الخيار')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الخيار (إنجليزي)')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تغيير السعر')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.productmodifiergroup', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'خيار معدّل',
                'verbose_name_plural': 'خيارات المعدّلات',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
