# Generated by Django 4.2.30 on 2026-04-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_supplier_linked_customer'),
        ('catalog', '0003_alter_product_category_alter_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_vendor',
            field=models.ForeignKey(blank=True, help_text='المورد/البائع صاحب المنتج الذي نبيعه بالنسبة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_products', to='purchasing.supplier', verbose_name='بائع النسبة'),
        ),
    ]
