# Generated by Django 4.2.30 on 2026-04-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_commission_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='الباركود'),
        ),
    ]
