# Generated by Django 4.2.30 on 2026-04-27 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='أجر اليوم')),
                ('work_days_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='أيام مستحقة / رصيد')),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='سلف معلقة')),
                ('store_purchases_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مشتريات من المقهى')),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='صافي الرصيد للموظف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('days_count', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الأيام')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المدفوع')),
                ('method', models.CharField(default='cash', max_length=16, verbose_name='طريقة الدفع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payouts', to='payroll.employee', verbose_name='الموظف')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'صرف راتب',
                'verbose_name_plural': 'صرف الرواتب',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCafePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_purchases', to='payroll.employee', verbose_name='الموظف')),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.saleinvoice', verbose_name='فاتورة مرتبطة')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'شراء موظف من المقهى',
                'verbose_name_plural': 'مشتريات الموظفين',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ السلفة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='payroll.employee', verbose_name='الموظف')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
            },
        ),
    ]
