# Generated by Django 4.2.27 on 2026-04-28 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='أجر الساعة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_hours_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ساعات عمل مستحقة'),
        ),
        migrations.AddField(
            model_name='employeeadvance',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advances', to='expenses.expense', verbose_name='مصروف رواتب مرتبط'),
        ),
        migrations.AddField(
            model_name='employeesalarypayout',
            name='advance_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='سلفة مخصومة من الصرف'),
        ),
        migrations.AddField(
            model_name='employeesalarypayout',
            name='hours_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الساعات'),
        ),
        migrations.AddField(
            model_name='employeesalarypayout',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payouts', to='expenses.expense', verbose_name='مصروف رواتب (النقد)'),
        ),
    ]
