# Generated by Django 4.2.27 on 2026-05-11 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_possettings_receipt_thermal_branding'),
        ('accounting', '0005_reclassify_employee_advances_expense'),
        ('payroll', '0003_employee_pay_type_monthly_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المحصّل')),
                ('method', models.CharField(default='cash', max_length=32, verbose_name='طريقة التحصيل')),
                ('store_portion', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='من مشتريات المقهى')),
                ('advance_portion', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='من السلف المعلّقة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_repayments', to='payroll.employee', verbose_name='الموظف')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_debt_repayments', to='accounting.journalentry', verbose_name='القيد اليومي')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'سداد ذمة موظف',
                'verbose_name_plural': 'سدادات ذمم الموظفين',
                'ordering': ('-created_at',),
            },
        ),
    ]
