# Generated by Django 4.2.27 on 2026-05-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('payroll', '0005_employee_linked_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='linked_customer',
            field=models.ForeignKey(blank=True, help_text='إن وُجد: أي بيع بالآجل على هذا العميل يُسجَّل تلقائياً في «مشتريات المقهى» وذمة الموظف.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_employee', to='contacts.customer', verbose_name='عميل مرتبط (آجل / طاولة)'),
        ),
    ]
