"""Views package — re-exports for urls and shell imports."""
from apps.purchasing.views._helpers import _supplier_opening_ledger_qs
from apps.purchasing.views._helpers import _supplier_opening_balance_from_ledger
from apps.purchasing.views._helpers import _apply_supplier_opening_balance
from apps.purchasing.views._helpers import _safe_purchase_redirect_next
from apps.purchasing.views._helpers import _apply_general_discount
from apps.purchasing.views._helpers import _purchasing_ctx
from apps.purchasing.views._helpers import _purchasing_reverse
from apps.purchasing.views._helpers import _purchasing_redirect
from apps.purchasing.views._helpers import _safe_return_path
from apps.purchasing.views._helpers import _purchase_invoice_detail_queryset
from apps.purchasing.views._helpers import _purchase_detail_back_url
from apps.purchasing.views._helpers import _redirect_open_purchase_invoice_to
from apps.purchasing.views._helpers import _redirect_open_purchase_invoice
from apps.purchasing.views._helpers import _purchase_invoice_detail_context
from apps.purchasing.views._helpers import _purchasing_tpl
from apps.purchasing.views.suppliers import supplier_list
from apps.purchasing.views.suppliers import supplier_detail
from apps.purchasing.views.suppliers import supplier_create
from apps.purchasing.views.suppliers import supplier_edit
from apps.purchasing.views.suppliers import supplier_delete
from apps.purchasing.views.suppliers import supplier_payment_create
from apps.purchasing.views.suppliers import supplier_link_customer
from apps.purchasing.views.invoices import purchase_invoice_create
from apps.purchasing.views.invoices import purchase_invoice_new
from apps.purchasing.views.invoices import purchase_invoice_list
from apps.purchasing.views.invoices import purchase_invoice_detail
from apps.purchasing.views.invoices import purchase_invoice_delete
from apps.purchasing.views.returns import purchase_return_create
from apps.purchasing.views.reports import supplier_statement
from apps.purchasing.views.reports import supplier_balances
from apps.purchasing.views.reports import commission_vendor_report
from apps.purchasing.views.panels import purchase_invoice_create_panel
from apps.purchasing.views.panels import supplier_create_panel
from apps.purchasing.views.panels import supplier_edit_panel
from apps.purchasing.views.panels import purchase_invoice_detail_panel
from apps.purchasing.views.search_api import purchase_products_search
from apps.purchasing.views.search_api import purchase_units_search
from apps.purchasing.views.search_api import purchase_unit_quick_create
from apps.purchasing.views.search_api import purchase_suppliers_search
from apps.purchasing.views.search_api import purchase_supplier_quick_create
from apps.purchasing.views.search_api import purchase_product_quick_create
