# Generated by Django 4.2.27 on 2026-04-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_payment_method_expand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(max_length=32, verbose_name='طريقة الدفع'),
        ),
    ]
