# Generated by Django 4.2.30 on 2026-04-27 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='ملغى')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('name_ar', models.CharField(max_length=80, verbose_name='اسم الطاولة')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='اسم الطاولة (إنجليزي)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طاولة',
                'verbose_name_plural': 'الطاولات',
                'ordering': ('sort_order', 'name_ar'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='ملغى')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('order_type', models.CharField(choices=[('dine_in', 'صالة'), ('takeaway', 'سفري'), ('delivery', 'توصيل')], max_length=16, verbose_name='نوع الطلب')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('checked_out', 'مكتمل الدفع'), ('cancelled', 'ملغى')], default='open', max_length=20, verbose_name='الحالة')),
                ('order_note', models.TextField(blank=True, verbose_name='ملاحظات الطلب')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='خصم مبلغ')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='خصم %')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer', verbose_name='العميل (ائتمان)')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.diningtable', verbose_name='الطاولة')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('line_note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة السطر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سطر طلب',
                'verbose_name_plural': 'أسطر الطلبات',
            },
        ),
    ]
