# Generated by Django 4.2.30 on 2026-04-27 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pos_advanced'),
        ('contacts', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_held',
            field=models.BooleanField(default=False, verbose_name='معلّق (Hold)'),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_batch_no',
            field=models.PositiveIntegerField(default=1, verbose_name='دفعة مطبخ حالية'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge_percent_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='خدمة % (فارغ = الافتراضي)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percent_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ضريبة % (فارغ = الافتراضي)'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='extra_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إضافة سعر من المعدّلات'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='kitchen_batch_no',
            field=models.PositiveIntegerField(default=1, verbose_name='دفعة مطبخ'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='modifiers_json',
            field=models.JSONField(blank=True, default=list, verbose_name='المعدّلات'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة الأساسي'),
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('guest_label', models.CharField(blank=True, max_length=160, verbose_name='اسم ضيف / بدون سجل')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('merged', 'مدموجة')], default='open', max_length=16, verbose_name='الحالة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer', verbose_name='عميل')),
                ('dining_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_sessions', to='pos.diningtable', verbose_name='الطاولة')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='pos.tablesession', verbose_name='دمجت في')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_sessions', to='core.worksession', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'جلسة طاولة',
                'verbose_name_plural': 'جلسات الطاولات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.tablesession', verbose_name='جلسة الطاولة'),
        ),
    ]
