# Generated by Django 4.2.27 on 2026-05-21 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_operation_mode_continuous'),
        ('pos', '0003_diningtable_ephemeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='ephemeral',
            field=models.BooleanField(default=False, help_text='طاولات تُنشأ من الكاشير وتُلغى تلقائياً عند إغلاق الجلسة — لا تُستخدم كطاولات ثابتة.', verbose_name='مؤقتة (كاشير)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.worksession', verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='work_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_sessions', to='core.worksession', verbose_name='الوردية'),
        ),
    ]
